In [ ]:
import pandas as pd 
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
# by default ascending
df.sort_values("english")

#decending
df.sort_values("english",ascending=False,inplace=True)
df

#by default ascending method 1
df.sort_values(by=['english'],ascending=[False])

# multiple cols sort
df.sort_values(by=['english','maths'],ascending=[False,True])

#a to z
df['name'] = df['name'].str.lower()
df.sort_values("name")

       name  gender  physics  maths  english
0      arun    Male       88     87       78
8    dinesh    Male       56     45       67
10    gowri  Female      100    100      100
9      hema  Female       71     90       23
13  jenifer  Female       67     88       90
7   kavitha  Female       78     71       67
2   moorthy    Male       89     90       70
12  murugan    Male       34     89       78
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
11      ram    Male       78     55       47
6    sundar    Male       12     67       67
4      usha  Female       67     45       78

In [3]:
import pandas as pd 
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [ ]:
df
# add coloumn total = py+math+english
df['total'] = df['english'] + df['maths'] + df['english']
df
#add row 
df.loc[14] = ["piyush",'Male',50,80,80,210]
df
#update coloum and update row

#delete coloum
df.drop("total",axis=1)
#delete row
df.drop(14,axis=0)

#delete row and delete coloum
df.drop()

       name  gender  physics  maths  english  total
10    gowri  Female      100    100      100    300
1    rajesh    Male       96    100       95    290
13  jenifer  Female       67     88       90    268
4      usha  Female       67     45       78    201
5     priya  Female       56     46       78    202
0      arun    Male       88     87       78    243
12  murugan    Male       34     89       78    245
2   moorthy    Male       89     90       70    230
7   kavitha  Female       78     71       67    205
6    sundar    Male       12     67       67    201
8    dinesh    Male       56     45       67    179
11      ram    Male       78     55       47    149
3      raja    Male       30     25       40    105
9      hema  Female       71     90       23    136
14   piyush    Male       50     80       80    210